"""Generate pytest test modules for a connector.

Inputs:
  - spec dict (from introspect.build_spec)
  - inventory (from analyze.analyze_file)
  - samples directory (path)
  - output directory (path)

Outputs (written to <output_dir>):
  - conftest.py
  - test_sdk_signatures.py    # one assertion per recorded call site
  - test_sdk_enums.py         # OAAPermission.X, OAAIdentityType.X attr refs
  - test_schema_contract.py   # CSV column existence + entity-relationship checks
  - test_import.py            # connector module imports cleanly

The generated tests are pure unit checks against the installed oaaclient
package and the source AST inventory — they do not execute the connector
or hit the network.
"""
from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Any


HEADER = '''"""AUTO-GENERATED by tools/oaa_test_loop — do not edit by hand.

Regenerate with: python -m tools.oaa_test_loop <slug>
"""
'''


def _classes(spec: dict[str, Any]) -> dict[str, dict[str, Any]]:
    """Flatten {module: {classes: {Name: ...}}} -> {Name: classdict}."""
    out: dict[str, dict[str, Any]] = {}
    for mod in spec.get("modules", {}).values():
        for name, cls in mod.get("classes", {}).items():
            out[name] = cls
    return out


def gen_import_test(slug: str, script_path: Path) -> str:
    return HEADER + f'''
import importlib.util
import sys
from pathlib import Path


SCRIPT = Path(__file__).resolve().parent.parent / "{script_path.name}"


def test_connector_module_imports():
    """The connector module must import without raising — this catches
    syntax errors, ImportError, NameError at module scope, missing deps."""
    spec = importlib.util.spec_from_file_location("{slug}_connector_under_test", SCRIPT)
    assert spec is not None, f"Could not load spec for {{SCRIPT}}"
    module = importlib.util.module_from_spec(spec)
    sys.modules["{slug}_connector_under_test"] = module
    spec.loader.exec_module(module)
'''


def gen_sdk_signature_tests(inv: dict[str, Any], spec: dict[str, Any]) -> str:
    classes = _classes(spec)
    lines: list[str] = [
        HEADER,
        "import pytest",
        "from oaaclient.templates import *  # noqa: F401,F403",
        "from oaaclient.client import *  # noqa: F401,F403",
        "",
        "# Each test below is generated from a real call site in the connector.",
        "# Failure means: method does not exist, kwarg name is wrong, or the",
        "# positional arg count exceeds what the SDK accepts.",
        "",
    ]
    seen: set[tuple[str, str, int, tuple[str, ...]]] = set()
    for idx, call in enumerate(inv.get("calls", [])):
        cls_name = call["target_class"]
        method = call["method"]
        key = (cls_name, method, call["positional_args"], tuple(sorted(call["keyword_args"])))
        # Generate one test per unique (class, method, shape).
        if key in seen:
            continue
        seen.add(key)
        cls = classes.get(cls_name)
        kwargs_repr = repr(call["keyword_args"])
        lineno = call["lineno"]
        test_name = f"test_call_{idx:03d}_{cls_name}_{method}_L{lineno}".replace("-", "_")
        if cls is None or method not in cls.get("methods", {}):
            available = sorted((cls or {}).get("methods", {}).keys())
            lines.extend([
                f"def {test_name}():",
                f"    available = {available!r}",
                f"    pytest.fail(",
                f"        f'{cls_name}.{method}() is not a method on the installed SDK '",
                f"        f'(connector line {lineno}). Available methods: ' + repr(available)",
                f"    )",
                "",
            ])
            continue
        method_spec = cls["methods"][method]
        param_names = [p["name"] for p in method_spec["params"]]
        # Exclude 'self' / 'cls' from positional-acceptance budget.
        skip = 1 if param_names and param_names[0] in ("self", "cls") else 0
        # Allowable param name set for kwargs:
        allowed_kw = [p["name"] for p in method_spec["params"][skip:]
                      if p["kind"] not in ("VAR_POSITIONAL", "VAR_KEYWORD")]
        accepts_var_kw = any(p["kind"] == "VAR_KEYWORD" for p in method_spec["params"])
        accepts_var_pos = any(p["kind"] == "VAR_POSITIONAL" for p in method_spec["params"])
        max_positional = len(allowed_kw) if not accepts_var_pos else 10_000

        lines.extend([
            f"def {test_name}():",
            f"    method = getattr({cls_name}, '{method}', None)",
            f"    assert method is not None, '{cls_name}.{method} not found'",
            f"    allowed = {allowed_kw!r}",
            f"    accepts_var_kw = {accepts_var_kw!r}",
            f"    pos = {call['positional_args']}",
            f"    max_pos = {max_positional}",
            f"    assert pos <= max_pos, (",
            f"        'Connector line {lineno}: {cls_name}.{method}() called with '",
            f"        f'{{pos}} positional args, but SDK accepts at most {{max_pos}} '",
            f"        f'(parameters: {{allowed}})'",
            f"    )",
            f"    for kw in {kwargs_repr}:",
            f"        if accepts_var_kw:",
            f"            continue",
            f"        assert kw in allowed, (",
            f"            f'Connector line {lineno}: {cls_name}.{method}() received '",
            f"            f'unknown kwarg \"{{kw}}\". Accepted: {{allowed}}'",
            f"        )",
            "",
        ])

    # Also test class constructions
    for idx, ctor in enumerate(inv.get("constructions", [])):
        cls_name = ctor["class_name"]
        cls = classes.get(cls_name)
        if cls is None:
            continue
        init = cls["methods"].get("__init__")
        if init is None:
            continue
        param_names = [p["name"] for p in init["params"]]
        skip = 1 if param_names and param_names[0] in ("self", "cls") else 0
        allowed_kw = [p["name"] for p in init["params"][skip:]
                      if p["kind"] not in ("VAR_POSITIONAL", "VAR_KEYWORD")]
        accepts_var_kw = any(p["kind"] == "VAR_KEYWORD" for p in init["params"])
        lineno = ctor["lineno"]
        test_name = f"test_ctor_{idx:03d}_{cls_name}_L{lineno}"
        lines.extend([
            f"def {test_name}():",
            f"    assert {cls_name!r} in globals(), '{cls_name} not importable via oaaclient'",
            f"    allowed = {allowed_kw!r}",
            f"    for kw in {ctor['keyword_args']!r}:",
            f"        if {accepts_var_kw!r}:",
            f"            continue",
            f"        assert kw in allowed, (",
            f"            f'Connector line {lineno}: {cls_name}(...) received unknown '",
            f"            f'kwarg \"{{kw}}\". Accepted: {{allowed}}'",
            f"        )",
            "",
        ])

    if len(lines) == 7:  # only header + initial blank lines
        lines.append("def test_no_sdk_calls_detected():")
        lines.append("    # Inventory contained no traceable oaaclient calls. This is")
        lines.append("    # likely a bug in the analyzer, not the connector — investigate.")
        lines.append("    import pytest")
        lines.append("    pytest.skip('no oaaclient calls detected in connector')")
        lines.append("")
    return "\n".join(lines)


def gen_sdk_enum_tests(inv: dict[str, Any], spec: dict[str, Any]) -> str:
    classes = _classes(spec)
    lines: list[str] = [
        HEADER,
        "import pytest",
        "",
        "# Verify every OAAPermission.X / OAAIdentityType.X / etc. referenced",
        "# in the connector actually exists on the SDK class.",
        "",
    ]
    seen: set[tuple[str, str]] = set()
    for idx, ref in enumerate(inv.get("attr_refs", [])):
        cls_name = ref["class_name"]
        attr = ref["attr"]
        key = (cls_name, attr)
        if key in seen:
            continue
        seen.add(key)
        cls = classes.get(cls_name)
        if cls is None:
            continue
        # Only check enum-like classes (those with attrs captured)
        if not cls.get("attrs"):
            continue
        valid = list(cls["attrs"].keys())
        lineno = ref["lineno"]
        test_name = f"test_enum_{idx:03d}_{cls_name}_{attr}_L{lineno}"
        lines.extend([
            f"def {test_name}():",
            f"    from oaaclient.templates import {cls_name}",
            f"    valid = {valid!r}",
            f"    assert hasattr({cls_name}, {attr!r}), (",
            f"        'Connector line {lineno}: {cls_name}.{attr} does not exist. '",
            f"        'Valid values: ' + repr(valid)",
            f"    )",
            "",
        ])
    if len(lines) == 5:
        lines.append("def test_no_enum_refs_detected():")
        lines.append("    import pytest")
        lines.append("    pytest.skip('no OAA enum references in connector')")
        lines.append("")
    return "\n".join(lines)


def _csv_columns(csv_path: Path) -> list[str]:
    """Read first row to get column headers. Best-effort; ignores parse errors."""
    try:
        with csv_path.open(newline="", encoding="utf-8-sig") as f:
            reader = csv.reader(f)
            return next(reader, [])
    except Exception:
        return []


def gen_schema_tests(inv: dict[str, Any], samples_dir: Path) -> str:
    lines: list[str] = [
        HEADER,
        "import csv",
        "from pathlib import Path",
        "import pytest",
        "",
        f"SAMPLES_DIR = Path({str(samples_dir)!r})",
        "",
    ]

    # Map sample CSV -> columns
    csv_files: dict[str, list[str]] = {}
    if samples_dir.exists():
        for f in samples_dir.glob("*.csv"):
            cols = _csv_columns(f)
            if cols:
                csv_files[f.name] = cols

    if not csv_files:
        lines.extend([
            "def test_no_sample_csvs_present():",
            "    pytest.skip('No CSV samples found in samples/; "
            "schema-contract tests skipped.')",
            "",
        ])
        return "\n".join(lines)

    # For each CSV, generate a fixture that verifies the file exists and columns are present.
    for idx, (fname, cols) in enumerate(sorted(csv_files.items())):
        safe = fname.replace(".", "_").replace("-", "_")
        lines.extend([
            f"def test_sample_csv_{idx:03d}_{safe}_present():",
            f"    p = SAMPLES_DIR / {fname!r}",
            f"    assert p.exists(), f'Sample CSV missing: {{p}}'",
            f"    with p.open(newline='', encoding='utf-8-sig') as f:",
            f"        header = next(csv.reader(f), [])",
            f"    assert header, f'Sample CSV {{p}} is empty'",
            "",
        ])

    # Aggregate referenced columns from the inventory. Filter to columns that
    # look like CSV-header candidates (uppercase / underscored / no spaces in
    # the case of JDE; we accept all strings to stay generic).
    all_csv_cols: set[str] = set()
    for cols in csv_files.values():
        all_csv_cols.update(cols)

    referenced = sorted({c["column"] for c in inv.get("column_refs", [])})
    # Heuristic: only assert columns that are referenced via a receiver named
    # 'row' or 'r' or 'record' or 'rec' (CSV row dicts). Skip generic dict refs.
    csv_like_receivers = {"row", "r", "record", "rec", "rows"}
    csv_refs = sorted({
        c["column"]
        for c in inv.get("column_refs", [])
        if c["receiver"].lower() in csv_like_receivers
    })

    if csv_refs:
        lines.extend([
            "REFERENCED_CSV_COLUMNS = " + repr(csv_refs),
            "",
            "ALL_SAMPLE_COLUMNS = " + repr(sorted(all_csv_cols)),
            "",
            "@pytest.mark.parametrize('col', REFERENCED_CSV_COLUMNS)",
            "def test_referenced_column_exists_in_some_sample(col):",
            "    assert col in ALL_SAMPLE_COLUMNS, (",
            "        f'Connector references CSV column {col!r}, but no sample CSV in '",
            f"        f'{{SAMPLES_DIR}} contains it. Available columns: {{ALL_SAMPLE_COLUMNS}}'",
            "    )",
            "",
        ])
    else:
        lines.append("# No CSV-row column references detected in connector.")
        lines.append("")

    return "\n".join(lines)


def gen_conftest(repo_root: Path, slug: str) -> str:
    return HEADER + f'''
import sys
from pathlib import Path

# Make the connector script importable as `{slug}_connector_under_test`
HERE = Path(__file__).resolve().parent
CONNECTOR_DIR = HERE.parent
if str(CONNECTOR_DIR) not in sys.path:
    sys.path.insert(0, str(CONNECTOR_DIR))
'''


def generate_all(
    *,
    slug: str,
    script: Path,
    samples_dir: Path,
    inventory: dict[str, Any],
    spec: dict[str, Any],
    out_dir: Path,
) -> dict[str, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    written: dict[str, Path] = {}
    files = {
        "conftest.py": gen_conftest(out_dir.parent, slug),
        "test_import.py": gen_import_test(slug, script),
        "test_sdk_signatures.py": gen_sdk_signature_tests(inventory, spec),
        "test_sdk_enums.py": gen_sdk_enum_tests(inventory, spec),
        "test_schema_contract.py": gen_schema_tests(inventory, samples_dir),
    }
    for name, content in files.items():
        path = out_dir / name
        path.write_text(content)
        written[name] = path
    # Also drop the inventory + spec snapshot for debugging
    (out_dir / "_inventory.json").write_text(json.dumps(inventory, indent=2))
    return written
