"""Orchestrator: discover connector → introspect → analyze → generate → run pytest.

CLI:
  python -m tools.oaa_test_loop <slug> [options]

Options:
  --no-regen       Skip test regeneration (run existing tests).
  --report PATH    Write structured JSON report to PATH (default:
                   ./integrations/<slug>/.test_report.json).
  --pytest-args .. Extra args to forward to pytest (e.g. "-k smoke").
  --venv PATH      Use a specific venv's python (default: auto-detect).

Exit codes:
  0   all tests passed
  1   one or more tests failed
  2   bad invocation / connector not found
  3   harness internal error
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]


@dataclass
class ConnectorPaths:
    slug: str
    base: Path
    script: Path
    samples_dir: Path
    tests_dir: Path
    venv_python: Path | None


def _autodiscover_script(base: Path, slug: str) -> Path | None:
    # Convention from CLAUDE.md: integrations/<slug>/<slug>.py
    candidate = base / f"{slug}.py"
    if candidate.exists():
        return candidate
    # Fallback: pick the largest .py file at the top of the dir
    pys = [p for p in base.glob("*.py") if not p.name.startswith("test_")]
    if not pys:
        return None
    return max(pys, key=lambda p: p.stat().st_size)


def _autodiscover_venv(base: Path) -> Path | None:
    candidates = [
        base / "venv" / "bin" / "python",
        base / "venv" / "bin" / "python3",
        base / ".venv" / "bin" / "python",
    ]
    for c in candidates:
        if c.exists():
            return c
    return None


def resolve_paths(slug: str, venv_override: str | None) -> ConnectorPaths:
    base = REPO_ROOT / "integrations" / slug
    if not base.exists():
        raise SystemExit(f"[harness] connector dir not found: {base}")
    script = _autodiscover_script(base, slug)
    if script is None:
        raise SystemExit(f"[harness] no .py connector script in {base}")
    samples = base / "samples"
    tests = base / "tests"
    if venv_override:
        venv_py: Path | None = Path(venv_override)
    else:
        venv_py = _autodiscover_venv(base)
    return ConnectorPaths(
        slug=slug,
        base=base,
        script=script,
        samples_dir=samples,
        tests_dir=tests,
        venv_python=venv_py,
    )


def _python_executable(venv_python: Path | None) -> str:
    if venv_python and venv_python.exists():
        return str(venv_python)
    return sys.executable


def _ensure_pytest(python: str) -> None:
    r = subprocess.run(
        [python, "-c", "import pytest"], capture_output=True, text=True
    )
    if r.returncode != 0:
        print("[harness] pytest not installed; installing into target python ...")
        subprocess.run([python, "-m", "pip", "install", "pytest"], check=True)


def regenerate_tests(paths: ConnectorPaths) -> dict[str, Any]:
    # Import locally so we can run harness with a different python than the one
    # that introspects oaaclient.
    from tools.oaa_test_loop import introspect, analyze, generate

    spec = introspect.build_spec()
    inv = analyze.analyze_file(paths.script, spec)
    # Clean previous generated tests but keep any user-authored ones.
    if paths.tests_dir.exists():
        for f in paths.tests_dir.glob("test_*.py"):
            head = f.read_text(errors="ignore")[:200]
            if "AUTO-GENERATED by tools/oaa_test_loop" in head:
                f.unlink()
        for f in (paths.tests_dir / "conftest.py",):
            if f.exists():
                head = f.read_text(errors="ignore")[:200]
                if "AUTO-GENERATED by tools/oaa_test_loop" in head:
                    f.unlink()
    written = generate.generate_all(
        slug=paths.slug,
        script=paths.script,
        samples_dir=paths.samples_dir,
        inventory=inv.to_dict(),
        spec=spec,
        out_dir=paths.tests_dir,
    )
    return {
        "spec_classes": sum(len(m["classes"]) for m in spec["modules"].values()),
        "spec_methods": sum(
            len(c["methods"]) for m in spec["modules"].values() for c in m["classes"].values()
        ),
        "calls_traced": len(inv.calls),
        "constructions_traced": len(inv.constructions),
        "attr_refs_traced": len(inv.attr_refs),
        "column_refs_traced": len(inv.column_refs),
        "unresolved_calls": len(inv.unresolved_calls),
        "files_written": {k: str(v) for k, v in written.items()},
    }


def run_pytest(paths: ConnectorPaths, extra_args: list[str]) -> dict[str, Any]:
    python = _python_executable(paths.venv_python)
    _ensure_pytest(python)
    junit = paths.tests_dir / "_junit.xml"
    cmd = [
        python, "-m", "pytest",
        str(paths.tests_dir),
        "-q", "--tb=short", "--no-header",
        f"--junitxml={junit}",
        *extra_args,
    ]
    env = os.environ.copy()
    env["PYTHONDONTWRITEBYTECODE"] = "1"
    proc = subprocess.run(cmd, capture_output=True, text=True, env=env, cwd=str(REPO_ROOT))
    failures = _parse_pytest_failures(proc.stdout + "\n" + proc.stderr)
    return {
        "exit_code": proc.returncode,
        "stdout": proc.stdout,
        "stderr": proc.stderr,
        "failures": failures,
        "junit_path": str(junit) if junit.exists() else None,
    }


def _parse_pytest_failures(out: str) -> list[dict[str, str]]:
    """Extract failing test names from pytest -q output.

    Looks for lines like:
        FAILED tests/test_x.py::test_y - AssertionError: ...
    """
    failures: list[dict[str, str]] = []
    for line in out.splitlines():
        line = line.strip()
        if line.startswith("FAILED "):
            rest = line[len("FAILED "):]
            if " - " in rest:
                nodeid, msg = rest.split(" - ", 1)
            else:
                nodeid, msg = rest, ""
            failures.append({"nodeid": nodeid, "message": msg})
        elif line.startswith("ERROR "):
            rest = line[len("ERROR "):]
            if " - " in rest:
                nodeid, msg = rest.split(" - ", 1)
            else:
                nodeid, msg = rest, ""
            failures.append({"nodeid": nodeid, "message": msg, "kind": "error"})
    return failures


def build_report(slug: str, regen: dict[str, Any] | None, pytest_run: dict[str, Any]) -> dict[str, Any]:
    return {
        "slug": slug,
        "exit_code": pytest_run["exit_code"],
        "passed": pytest_run["exit_code"] == 0,
        "summary": _summary_line(pytest_run["stdout"]),
        "regeneration": regen,
        "failures": pytest_run["failures"],
        "stdout_tail": "\n".join(pytest_run["stdout"].splitlines()[-60:]),
        "stderr_tail": "\n".join(pytest_run["stderr"].splitlines()[-20:]),
    }


def _summary_line(out: str) -> str:
    for line in reversed(out.splitlines()):
        if " passed" in line or " failed" in line or " error" in line:
            return line.strip()
    return ""


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(prog="tools.oaa_test_loop")
    parser.add_argument("slug", help="connector slug under ./integrations/")
    parser.add_argument("--no-regen", action="store_true", help="skip test regeneration")
    parser.add_argument("--report", default=None, help="path for JSON report")
    parser.add_argument("--venv", default=None, help="path to venv python to use")
    parser.add_argument("--pytest-args", default="", help="extra args forwarded to pytest")
    args = parser.parse_args(argv[1:])

    paths = resolve_paths(args.slug, args.venv)
    regen = None if args.no_regen else regenerate_tests(paths)
    pytest_run = run_pytest(paths, args.pytest_args.split() if args.pytest_args else [])
    report = build_report(args.slug, regen, pytest_run)
    report_path = Path(args.report) if args.report else (paths.base / ".test_report.json")
    report_path.write_text(json.dumps(report, indent=2))

    # Human-readable summary on stderr so JSON-on-stdout is parseable.
    print(f"[harness] {paths.slug}: {report['summary']}", file=sys.stderr)
    if report["failures"]:
        print(f"[harness] failures ({len(report['failures'])}):", file=sys.stderr)
        for f in report["failures"][:20]:
            print(f"  - {f['nodeid']}  {f.get('message','')}", file=sys.stderr)
    print(f"[harness] report: {report_path}", file=sys.stderr)
    return pytest_run["exit_code"]


if __name__ == "__main__":
    sys.exit(main(sys.argv))
